### ISSUE TITLE
nil email string handling

### ISSUE THREAD

**Issue by saniul** [mparticle-integrations/mparticle-apple-integration-appsflyer#3]
I was about to submit a patch that's similar to this https://github.com/mparticle-integrations/mparticle-apple-integration-appsflyer/commit/9c2a1d8f1e6bbb0e9b363d11e003de3008e451ce. Have you considered submitting an empty array for the `nil` case instead of just failing the call?

**Comment by kballard** [comment]
Agreed. The problem with the current approach is if the user logs out, AppsFlyer is not notified of this fact.

**Comment by samdozor** [comment]
Hey @saniul / @kballard we've put a request to the AppsFlyer team for the best way to handle this situation.
