### ISSUE TITLE
AppsFlyer ID integration attribute is not being set correctly

### ISSUE THREAD

**Issue by saniul** [mparticle-integrations/mparticle-apple-integration-appsflyer#4]
[This condition](https://github.com/mparticle-integrations/mparticle-apple-integration-appsflyer/commit/0d1d679bfc7f8083039aa78b106271619466ce5e#diff-f3facda5d3ff2ec53af1879bc4fa52c6R75) should be flipped, you only want to set the integration attributes if `appsFlyerUID` is not `nil.

There's also a possible crash here - when `appsFlyerUID` is `nil`, you're trying to put it in a dictionary which will result in an exception.

**Comment by samdozor** [comment]
@saniul should be all set here.
