### ISSUE TITLE
mParticle-AppsFlyer and mParticle-UrbanAirship integration?

### ISSUE THREAD

**Issue by nataliab** [mparticle-integrations/mparticle-apple-integration-appsflyer#8]
When using mParticle-AppsFlyer and mParticle-UrbanAirship, is there a way to link AppsFlyer and UrbanAirship via: 
```
NSString  *channelID = [UAPush shared].channelID;
[[AppsFlyerTracker sharedTracker] setAdditionalData:@{@"ios_channel" : channelID }]; 
```

Where/when should this code be inserted?

See: https://support.appsflyer.com/hc/en-us/articles/207033976-Urban-Airship-Integration

**Comment by samdozor** [comment]
Hey @nataliab! We may actually be able to do all of this server-side via our AppsFlyer attribution feed, [documented here](http://docs.mparticle.com/#appsflyer-feed). I'm going to engage our implementation team so we can continue the conversation there.

**Comment by nataliab** [comment]
@samdozor That would be great! I'm looking forward to your updates!
